### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by rsalz** [debbiemarkslab/plmc#6]
I am trying to run plmc to get parameters for use with EVmutation. The program works fine when I use the examples given in the example folder but when I put in my own sequence alignments I always get output similar to this:

100 valid sequences out of 100
724 sites
Effective number of samples: 75.2       (80% identical neighborhood = 1.000 samples)
Gradient optimization: OUTOFMEMORY
Error writing parameters

My alignment is in fasta format, aligned with MAFFT. I tried redownloading and configuring a different way. How can I get this program to work...

**Comment by jingraham** [comment]
Unfortunately, the memory requirements typically go with L^2, where L is the length of the protein and the factor is independent of the number of sequences. So, even though you have only 100 sequences, the 724^2 will still require lots of RAM. 

How much RAM does the machine you are using have? Some empirical predictions for RAM requirements are available from @aggreen in debbiemarkslab/EVcouplings#28.

One option that reduces memory requirements by a factor of ~2 is to compile with `make all-openmp32` or `make all-32` rather than `make all-openmp` or `make all`.
